server:
  port: 8081

spring:
  application:
    name: display

product:
  ribbon:
#    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true

hystrix:
  command:
    productInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1 # Minimum number of request to calculate circuit brearker's health default 20
        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50